stages:
  - test
  - package
  - publish

testing:
  stage: test
  image: registry.gitlab.com/redmic-project/docker/python-postgres:latest
  variables:
    PIP_CACHE_DIR: "${CI_PROJECT_DIR}/pip-cache"
  before_script:
    - pip3 install -r requirements.txt
  script:
    - su -c nosetests gitlab

packaging:
  stage: package
  image: python:3.6
  variables:
    PIP_CACHE_DIR: "${CI_PROJECT_DIR}/pip-cache"
  script:
    - python setup.py sdist bdist_wheel
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}"
    expire_in: '6 months'
    paths:
      - dist/*

publishing:
  stage: publish
  image: python:3.6
  variables:
    PIP_CACHE_DIR: "${CI_PROJECT_DIR}/pip-cache"
  before_script:
    - pip install twine
  script:
    - >
      twine upload dist/*
      --username ${PYPI_USERNAME} --password ${PYPI_PASSWORD}